openapi: 3.0.1
info:
  title: playground
  description: API Definition of playground
  version: 1.0.0
servers:
- url: http://localhost:8290/playground
paths:
  /:
    get:
      responses:
        default:
          description: Default response
