openapi: 3.0.1
info:
  title: playground
  description: API Definition of playground
  version: 1.0.0
servers:
- url: http://localhost:8290/playground
paths:
  /gender:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
  /inner-xml:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
